### PR TITLE
simplify, FileWrapper, Berksfile and tests

### PR DESCRIPTION
**Pull request by samstav**
Berksfile and MetadataRb are now their own instances and share the same code in FileWrapper (`write_statements()`) for neatly writing new lines into them. 

#### todo

- [x] Get the MetadataRb implementation caught up to Berksfile (needs from_dict(), merge(), etc.)
- [x] Write  e2e and deeper functional tests

side note: Pays back some technical debt from the first week of writing.

### CODE REVIEW

**Comment by samstav** [comment]
@jarosser06 Berksfile now understands `source` statements and will properly handle them when merging Berksfiles. See these tests for an example:

https://github.com/samstav/fastfood/blob/berksfile_class/tests/test_berks.py

**Comment by jarosser06** [comment]
@samstav Are you ready for this to be merged?

**Comment by samstav** [comment]
@jarosser06 ready if it passes tests.

**Comment by samstav** [comment]
WOMM problems...

**Comment by samstav** [comment]
@jarosser06 ready

**Comment by jarosser06** [comment]
@samstav Yeah I'll make a separate PR with some more rigorous tests.

**Pull request merged**
